### ISSUE TITLE
Allow env-derived constants in YML config

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-csp-headers#13]
If I want to take an S3 bucket host from an environment variable, I should be able to surround it with backticks in YML and the module should interpolate it correctly. 

To acheive this, `Extensons/ControllerCSPExtension` needs to be patched with a call to `Injector::convertServiceProperty()` as follows:

Example YML:

```yml
...
    img-src:
      allow:
        - '`AWS_BUCKET_NAME`'
      blob: false
      self: true
      data: true
...
```

Patched logic:

```php
...
    public function onAfterInit()
    {
        /** @var Controller $owner */
        $owner = $this->owner;
        if ($this->addPolicyHeaders) {
            $config = Injector::inst()->convertServiceProperty(CSPBackend::config()->get('csp_config'));
...
```
