### ISSUE TITLE
BUG: could not get 'unsafe-inline' for script-src, but works fine for style-src

### ISSUE THREAD

**Issue by sunnysideup** [Firesphere/silverstripe-csp-headers#51]
Here is my csp:
```yml

---
Name: app-csp
---
Firesphere\CSPHeaders\View\CSPBackend:
  csp_config:
    enabled: true

    # report
    report-only: false
    report-uri: '...'

    # base
    base-uri:
      allow: []
      self: true

    # default
    default-src:
      self: true
      allow:
        - fonts.googleapis.com
        - fonts.gstatic.com
        - '*.gstatic.com'
        - 't0.gstatic.com'
        - 'checkcheck.sunnysideup.co.nz'
    # iframes
    frame-src:
      self: false
      allow: []

    # connect
    connect-src:
      allow: []
      self: true

    # font
    font-src:
      allow:
        - fonts.googleapis.com
        - fonts.gstatic.com
      self: true

    # form
    form-action:
      self: true

    # frame ancestors
    frame-ancestors: []

    # images
    img-src:
      allow:
        - '*.gstatic.com'
        - 't0.gstatic.com'
      blob: true
      self: true
      data: true

    # media
    media-src:
      allow: []

    object-src: []

    plugin-types: []

    script-src:
      allow:
        - fonts.googleapis.com
        - "'unsafe-inline'"
      self: true
      unsafe-inline: true
      # unsafe-eval: false

    style-src:
      allow:
        - fonts.googleapis.com
      self: true
      unsafe-inline: true

    upgrade-insecure-requests: true

  useNonce: true

  jsSRI: false

  cssSRI: false

Firesphere\CSPHeaders\Builders\SRIBuilder:
  skip_domains:
    - 'https://fonts.googleapis.com/'
    - 'https://fonts.gstatic.com/'
    - 'https://t0.gstatic.com/'
    - 'https://checkcheck.sunnysideup.co.nz'

Firesphere\CSPHeaders\Models\SRI:
  clear_sri_on_build: true

  HSTS:
    enabled: true
    max-age: 3600
    include_subdomains: true

  referrer: same-origin
  frame-options: SAMEORIGIN
  content-type-options: nosniff
---
Only:
  environment: 'dev'
---
Firesphere\CSPHeaders\View\CSPBackend:
  jsSRI: false

  csp_config:
    report-only: true

  upgrade-insecure-requests: false

```

Note that, to make it work, I did this:

```yml
    script-src:
      allow:
        - fonts.googleapis.com
        - "'unsafe-inline'"
      self: true
      unsafe-inline: true
      # unsafe-eval: false

```

The original was:

```yml
    script-src:
      allow: []
      self: true
      unsafe-inline: true
      unsafe-eval: false
```
