### ISSUE TITLE
Docs recommendation - note "After" requirement as you may not realise that module sets its own directives already. 

### ISSUE THREAD

**Issue by sunnysideup** [Firesphere/silverstripe-csp-headers#53]
To set your own rules, you should have something like this:

`app/_config/csp.yml`:

```yml
---
Name: app-csp
After: '#CSPHeaders'
---
# my directives go here. 
```
